name: Reuse

on:
  workflow_call:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.SUPER_SECRET }}
          MY_VAL2: ${{ secrets.TOKEN }}
        run: |
          import os
          print("FIRST")
          for q in (os.getenv("MY_VAL")):
            print(q)
          print("second")
          for q in (os.getenv("MY_VAL2")):
          print(q)
        shell: python
    
