name: Reuse

on:
  workflow_call:
    secrets:
      TOKEN:
        description: 'A token passed from the caller workflow'
        required: true

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.SUPER_SECRET }}
          MY_VAL2: ${{ secrets.TOKEN }}
        run: |
          import os
          print("FIRST")
          for q in (os.getenv("MY_VAL")):
            print(q)
          print("second")
          for q in (os.getenv("MY_VAL2")):
            print(q)
        shell: python
  print2:
    uses: strbbrn/reuse1/.github/workflows/reuse1.yml@main
